import type { Metadata } from 'next';
import { Epilogue } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layouts/Navbar';

const epilogue = Epilogue({ subsets: ['latin-ext'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${epilogue.className} relative overflow-x-hidden`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
